### ISSUE TITLE
it works with sign-in page but not on the sign-up page

### ISSUE THREAD

**Issue by Vander-Ng** [humhub-contrib/auth-google#4]
Even though I can successfully configure the module (I think that’s the case…), I can only see the Google button on the Sign-in screen, but not on the Sign-up screen, which is contradict to what the module mentioned.
![IMG_1961 2](https://user-images.githubusercontent.com/78061132/154797299-6d843e11-9800-4ccf-8a5f-a5b927d7d787.PNG)
![IMG_1962 2](https://user-images.githubusercontent.com/78061132/154797302-28c8a83f-3a6c-4dee-aff4-fb38b0d32b6e.PNG)

**Comment by ArchBlood** [comment]
See https://github.com/humhub/humhub/issues/3593

**Comment by luke-** [comment]
@Vander-Ng Even though they are slightly different, I would combine this in the existing issue.
